
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 23 18:08:37 CDT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 72;
  public static final int Llave_c = 46;
  public static final int Incremento = 42;
  public static final int ComparadorIgual = 13;
  public static final int Llave_a = 45;
  public static final int Std = 77;
  public static final int Comilla_simple = 11;
  public static final int Linea = 44;
  public static final int Break = 5;
  public static final int Coma = 10;
  public static final int Parent_c = 66;
  public static final int Parent_a = 65;
  public static final int Corchete_c = 17;
  public static final int True = 82;
  public static final int MenorQue = 52;
  public static final int Corchete_a = 16;
  public static final int Long = 47;
  public static final int Punto = 69;
  public static final int Default = 19;
  public static final int Char = 8;
  public static final int Decremento = 21;
  public static final int For = 36;
  public static final int BitAnd = 3;
  public static final int Et = 33;
  public static final int Void = 85;
  public static final int DosPuntos = 29;
  public static final int Else = 30;
  public static final int Negador = 60;
  public static final int Resta = 71;
  public static final int BitOr = 4;
  public static final int Int = 40;
  public static final int Cin = 9;
  public static final int Using = 84;
  public static final int Suma = 75;
  public static final int Y_logico = 87;
  public static final int ERROR = 32;
  public static final int DobleMenor = 28;
  public static final int Typedef = 81;
  public static final int MenorIgual = 54;
  public static final int Main = 48;
  public static final int Do = 25;
  public static final int _String = 78;
  public static final int P_coma = 67;
  public static final int Unsigned = 83;
  public static final int MayorQue = 51;
  public static final int MasIgual = 49;
  public static final int MultiplicacionIgual = 58;
  public static final int Short = 74;
  public static final int MenosIgual = 50;
  public static final int Scanf = 73;
  public static final int Case = 7;
  public static final int Const = 14;
  public static final int ModuloIgual = 56;
  public static final int Endl = 31;
  public static final int DivisionIgual = 24;
  public static final int Continue = 15;
  public static final int Byte = 6;
  public static final int Numeral = 63;
  public static final int _System = 76;
  public static final int If = 38;
  public static final int STRING_LITERAL = 88;
  public static final int MayorIgual = 53;
  public static final int O_logico = 64;
  public static final int Define = 20;
  public static final int EOF = 0;
  public static final int Bool = 2;
  public static final int Cout = 18;
  public static final int Numero = 61;
  public static final int Double = 26;
  public static final int Struct = 79;
  public static final int Division = 23;
  public static final int Namespace = 59;
  public static final int error = 1;
  public static final int False = 34;
  public static final int Diferente = 22;
  public static final int Comillas = 12;
  public static final int Float = 35;
  public static final int Iostream = 43;
  public static final int Identificador = 37;
  public static final int DobleMayor = 27;
  public static final int Include = 41;
  public static final int Modulo = 55;
  public static final int Printf = 68;
  public static final int NumeroDecimal = 62;
  public static final int Register = 70;
  public static final int Igual = 39;
  public static final int While = 86;
  public static final int Switch = 80;
  public static final int Multiplicacion = 57;
}

